### ISSUE TITLE
Support for schemas generated using marshmallow-sqlalchemy

### ISSUE THREAD

**Issue by dev-zero** [marshmallow-code/webargs#126]
I am using marshmallow-sqlalchemy via Flash-Marshmallow to auto-generate a schema using a SQLAlchemy model with the following schema definition and Flask-RESTful resource:

``` python
from flask_marshmallow import Marshmallow
from webargs import fields
from webargs.flaskparser import use_kwargs

from . import app
from .models import Calculation

ma = Marshmallow(app)

class CalculationSchema(ma.ModelSchema):
    test = fields.Str(attribute='test.name', dump_only=True)

    class Meta:
        model = Calculation
        strict = True

class CalculationListResource(Resource):
    @use_kwargs(CalculationSchema())
    def post(self, collection, structure, pseudo, basis_set,
             settings, restrictions):
        pass
```

what I get when I try to POST with the correct arguments is:

```
Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib64/python3.5/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib64/python3.5/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/lib64/python3.5/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/lib64/python3.5/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib64/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib64/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib64/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib64/python3.5/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/lib64/python3.5/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/lib64/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib64/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib64/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib64/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib64/python3.5/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib64/python3.5/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/lib64/python3.5/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/lib64/python3.5/site-packages/webargs/core.py", line 431, in wrapper
    force_all=force_all)
  File "/usr/lib64/python3.5/site-packages/webargs/core.py", line 362, in parse
    fill_in_missing_args(ret, schema)
  File "/usr/lib64/python3.5/site-packages/webargs/core.py", line 78, in fill_in_missing_args
    missing_args = all_field_names - set(ret.keys())
AttributeError: 'Calculation' object has no attribute 'keys'

-->
```

Not sure whether this bug should rather be reported against marshmallow-sqlalchemy, though.

**Comment by avilaton** [comment]
@dev-zero please add more info. How is the `Calculation` model defined and what is the payload you are POSTing?

**Comment by dev-zero** [comment]
the definition of the calculation model is:

``` python
from flask_sqlalchemy import SQLAlchemy
db = SQLAlchemy(app)

def UUIDPKColumn():
    """Constructs a Primary Key UUID Column"""
    return Column(UUID(as_uuid=True), server_default=text("gen_random_uuid()"),
                  primary_key=True)

class Calculation(db.Model):
    id = UUIDPKColumn()

    collection_id = Column(UUID(as_uuid=True),
                           ForeignKey('calculation_collection.id'),
                           nullable=False)
    collection = relationship("CalculationCollection", backref="calculations")

    test_id = Column(Integer, ForeignKey('test.id'))
    test = relationship("Test", backref="calculations")

    structure_id = Column(UUID(as_uuid=True), ForeignKey('structure.id'),
                          nullable=False)
    structure = relationship("Structure", backref="calculations")

    code_id = Column(UUID(as_uuid=True),
                     ForeignKey('code.id'),
                     nullable=False)
    code = relationship("Code", backref="calculations")

    pseudos = relationship("Pseudopotential",
                           secondary="calculation_pseudopotential",
                           backref="calculations")
    basis_sets = relationship("BasisSet",
                              secondary="calculation_basis_set",
                              backref="calculations")

    settings = Column(JSONB)
    restrictions = Column(JSONB)
    results = Column(JSONB)

    def __repr__(self):
        return "<Calculation(id='{}')>".format(self.id)
```

The curl call was something like the following (if I remember correctly, since I don't have the original one anymore):

```
curl -X POST 'localhost:5000/api/v2/calculations?collection=23a7027a-47de-4290-9aa4-ce2fe17ea06c&structure=ee99d612-56bf-4af2-ba5a-da85b356527d&code=e3109f42-52d2-4bc5-8c3c-8b94fcf2f6d6'
```

**Comment by sloria** [comment]
@dev-zero You are seeing that error because Schemas generated with marshmallow-sqlalchemy deserialize data to a `Model` instance (i.e. a `Calculation`) by default.  If you use `use_kwargs`, the Schema you pass must return a `dict`.

Two solutions:
- Use `use_kwargs` and override the `make_instance` hook of your schema

``` python
class CalculationSchema(ma.ModelSchema):
    test = fields.Str(attribute='test.name', dump_only=True)

    class Meta:
        model = Calculation
        strict = True

    @ma.post_load
    def make_instance(self, data):
        # Return deserialized data as a dict, not a model instance
        return data

class CalculationListResource(Resource):
    @use_kwargs(CalculationSchema())
    def post(self, collection, structure, pseudo, basis_set,
             settings, restrictions):
        pass
```
- Use `use_args` , which will pass the model instance to your view

``` python
class CalculationSchema(ma.ModelSchema):
    test = fields.Str(attribute='test.name', dump_only=True)

    class Meta:
        model = Calculation
        strict = True

    @ma.post_load
    def make_instance(self, data):
        # Return deserialized data as a dict, not a model instance
        return data

class CalculationListResource(Resource):
    @use_args(CalculationSchema())
    def post(self, calculation):
        # NOTE: Calculation is a model instance
        pass
```

**Comment by sloria** [comment]
I've added a note in the docs which will hopefully clarify this behavior.
