### ISSUE TITLE
Documentation Requires Python 3.4 or Greater

### ISSUE THREAD

**Issue by rgant** [marshmallow-code/webargs#156]
Not that I have a problem with that, but I was basing all of my work around 2.7 since that appeared to me to be the developer's preferred python version.  This is the error I get trying to install `pip install -r docs/requirements.txt` as per the docs on py27:

```
Requirement already satisfied: marshmallow in /Users/rgant/.pyenv/versions/2.7.13/envs/vwebargs/lib/python2.7/site-packages (from -r docs/../dev-requirements.txt (line 2))
Requirement already satisfied: invoke==0.13.0 in /Users/rgant/.pyenv/versions/2.7.13/envs/vwebargs/lib/python2.7/site-packages (from -r docs/../dev-requirements.txt (line 5))
Requirement already satisfied: pytest==3.0.3 in /Users/rgant/.pyenv/versions/2.7.13/envs/vwebargs/lib/python2.7/site-packages (from -r docs/../dev-requirements.txt (line 8))
Requirement already satisfied: tox==2.4.1 in /Users/rgant/.pyenv/versions/2.7.13/envs/vwebargs/lib/python2.7/site-packages (from -r docs/../dev-requirements.txt (line 9))
Requirement already satisfied: mock==2.0.0 in /Users/rgant/.pyenv/versions/2.7.13/envs/vwebargs/lib/python2.7/site-packages (from -r docs/../dev-requirements.txt (line 10))
Requirement already satisfied: webtest==2.0.23 in /Users/rgant/.pyenv/versions/2.7.13/envs/vwebargs/lib/python2.7/site-packages (from -r docs/../dev-requirements.txt (line 11))
Requirement already satisfied: wheel in /Users/rgant/.pyenv/versions/2.7.13/envs/vwebargs/lib/python2.7/site-packages (from -r docs/../dev-requirements.txt (line 14))
Requirement already satisfied: twine==1.8.1 in /Users/rgant/.pyenv/versions/2.7.13/envs/vwebargs/lib/python2.7/site-packages (from -r docs/../dev-requirements.txt (line 15))
Requirement already satisfied: Flask>=0.10.1 in /Users/rgant/.pyenv/versions/2.7.13/envs/vwebargs/lib/python2.7/site-packages (from -r docs/../dev-requirements.txt (line 18))
Requirement already satisfied: Django>=1.6.5 in /Users/rgant/.pyenv/versions/2.7.13/envs/vwebargs/lib/python2.7/site-packages (from -r docs/../dev-requirements.txt (line 19))
Requirement already satisfied: bottle>=0.12.10 in /Users/rgant/.pyenv/versions/2.7.13/envs/vwebargs/lib/python2.7/site-packages (from -r docs/../dev-requirements.txt (line 20))
Requirement already satisfied: tornado>=4.0 in /Users/rgant/.pyenv/versions/2.7.13/envs/vwebargs/lib/python2.7/site-packages (from -r docs/../dev-requirements.txt (line 21))
Requirement already satisfied: pyramid>=1.5.2 in /Users/rgant/.pyenv/versions/2.7.13/envs/vwebargs/lib/python2.7/site-packages (from -r docs/../dev-requirements.txt (line 22))
Requirement already satisfied: webapp2>=2.5.2 in /Users/rgant/.pyenv/versions/2.7.13/envs/vwebargs/lib/python2.7/site-packages (from -r docs/../dev-requirements.txt (line 23))
Requirement already satisfied: falcon>=0.3.0 in /Users/rgant/.pyenv/versions/2.7.13/envs/vwebargs/lib/python2.7/site-packages (from -r docs/../dev-requirements.txt (line 24))
Requirement already satisfied: flake8==2.4.1 in /Users/rgant/.pyenv/versions/2.7.13/envs/vwebargs/lib/python2.7/site-packages (from -r docs/../dev-requirements.txt (line 27))
Collecting aiohttp>=1.0.0 (from -r docs/../dev-requirements-py3.txt (line 2))
  Using cached aiohttp-1.3.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/45/jgwr22wn70q3151rld4xmjm40000gn/T/pip-build-AQKurb/aiohttp/setup.py", line 61, in <module>
        raise RuntimeError("aiohttp requires Python 3.4.2+")
    RuntimeError: aiohttp requires Python 3.4.2+
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/45/jgwr22wn70q3151rld4xmjm40000gn/T/pip-build-AQKurb/aiohttp/
```

Personally I think that webargs should stop supporting python versions other than 3.5, 2.7, and add support for 3.6 soon.

**Comment by rgant** [comment]
In python 35 I get this error:
```
/Users/rgant/Programming/True-Impact/webargs/docs/api.rst:59: WARNING: autodoc: failed to import module 'webargs.webapp2parser'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/rgant/.pyenv/versions/3.5.3/envs/vwebargs/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 386, in import_object
    __import__(self.modname)
  File "/Users/rgant/Programming/True-Impact/webargs/webargs/webapp2parser.py", line 31, in <module>
    import webapp2
  File "/Users/rgant/.pyenv/versions/3.5.3/envs/vwebargs/lib/python3.5/site-packages/webapp2.py", line 571
    except Exception, e:
```

**Comment by rgant** [comment]
I forced webapp2 to the 3.0.0b1 version to resolve this issue.

`pip install webapp2==3.0.0b1`

**Comment by sloria** [comment]
Thanks for reporting @rgant . I've updated webapp2 in dev-requirements.txt to install version 3.0.0b1 at a minimum.

> Personally I think that webargs should stop supporting python versions other than 3.5, 2.7, and add support for 3.6 soon.

webargs already supports 3.6. We will likely drop support for 2.6 and 3.3 with the next major release.
