### ISSUE TITLE
ValidationError is no longer handled correctly by flask-restful

### ISSUE THREAD

**Issue by kardaj** [marshmallow-code/webargs#305]
We have been noticing a new behaviour in our APIs after upgrading from `3.x` to `4.x`.  Here's an example that illustrates the problem, consider this a `main.py` file:

```python
from marshmallow import Schema, validate
from flask import Flask
from webargs import fields
from webargs.flaskparser import use_kwargs
from flask_restful import Resource, Api


class MySchema(Schema):
    class Meta:
        strict = True
    email = fields.String(location='json', validate=validate.Email(), required=True)


app = Flask(__name__)
api = Api(app)


class PersonalInfo(Resource):
    @use_kwargs(MySchema)
    def put(self, email):
        print email
        return {'hello': 'world'}


api.add_resource(PersonalInfo, '/')


if __name__ == "__main__":
    app.run()
```
Previous behaviour:
```bash
$ pip installl 'webargs<4.0.0'
$ python main.py

$ curl -X PUT http://127.0.0.1:5000/ -d email=hello -i
HTTP/1.0 422 UNPROCESSABLE ENTITY
Content-Type: application/json
Content-Length: 62
Server: Werkzeug/0.14.1 Python/2.7.15
Date: Tue, 16 Oct 2018 15:04:31 GMT

{"messages": {"email": ["Missing data for required field."]}}
```
Current behaviour:
```bash
$ pip install 'webargs>=4.0.0' --upgrade
$ python main.py

$ curl -X PUT http://127.0.0.1:5000/ -d email=hello -i
HTTP/1.0 500 INTERNAL SERVER ERROR
Content-Type: application/json
Content-Length: 37
Server: Werkzeug/0.14.1 Python/2.7.15
Date: Tue, 16 Oct 2018 15:11:01 GMT

{"message": "Internal Server Error"}
```
The error I get is:
```
[2018-10-16 17:11:01,398] ERROR in app: Exception on / [PUT]
Traceback (most recent call last):
  File "/Users/hassene/Projects/personal/housing-market/env/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/hassene/Projects/personal/housing-market/env/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/hassene/Projects/personal/housing-market/env/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/Users/hassene/Projects/personal/housing-market/env/lib/python2.7/site-packages/flask/app.py", line 1695, in handle_user_exception
    assert exc_value is e
AssertionError
```
Any idea where this is coming from?

**Comment by sloria** [comment]
You need to use a custom error handler when using webargs with Flask-RESTful. See the example here: https://github.com/sloria/webargs/blob/56dabfe1c6644b320c9e5ce24626007696659faf/examples/flaskrestful_example.py#L71-L77

**Comment by kardaj** [comment]
Thanks!
