### ISSUE TITLE
Error upgrading from 3.0.2 to 4.1.2

### ISSUE THREAD

**Issue by bouzafr** [marshmallow-code/webargs#331]
I just upgraded from 3.0.2 to 4.1.2 and got the error below. Anything I can do to fix this?

Thanks.

```
Traceback (most recent call last):
  File "/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/venv/lib/python3.6/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/venv/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/venv/lib/python3.6/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/venv/lib/python3.6/site-packages/webargs/core.py", line 474, in wrapper
    force_all=force_all,
  File "/venv/lib/python3.6/site-packages/webargs/core.py", line 396, in parse
    self._on_validation_error(error, req, schema)
  File "/venv/lib/python3.6/site-packages/webargs/core.py", line 334, in _on_validation_error
    self.error_callback(error, req, schema)
TypeError: handle_request_parsing_error() takes 2 positional arguments but 3 were given
```

**Comment by lafrech** [comment]
This is a documented breaking change: https://webargs.readthedocs.io/en/latest/changelog.html#id4.

> Custom error handlers receive the marshmallow.Schema instance as the third argument. Update any functions decorated with Parser.error_handler to take a schema argument.
