### ISSUE TITLE
Webargs 5.0.0 incorrectly tries to parse JSON body for GET request

### ISSUE THREAD

**Issue by kirsle** [marshmallow-code/webargs#357]
Upon upgrading to webargs >= 5.0.0 we started to see some failures in our automated unit tests (Flask with webargs-flaskparser).

We had this simple Flask endpoint which uses a GET request and has `?page=1&per_page=20` query parameters:

```python
@api.route('/users')
@use_kwargs({
    "page": fields.Int(missing=1),
    "per_page": fields.Int(missing=20),
})
def get_users(page, per_page):
    users = User.query.paginate(page, per_page, False)
    data = {
        'users': [x.to_json() for x in users.items]
    }

    return responses.success(data, paginate=users)
```

And our unit test used a simple Flask test client:

```python
client = app.test_client()
rv = client.get("/v1/users")
```

If I dummy out the whole `@use_kwargs` block and provide function default values, the endpoint was able to run without error. I printed the request headers and body to see what they look like for the test client, and I got:

```python
>>> print(request.headers)
EnvironHeaders([('Host', 'localhost'), ('Content-Length', '0'), ('User-Agent', 'werkzeug/0.14.1')])
>>> print(request.data)
b''
```

As we can see, the request did not send a Content-Type header and the webargs.flaskparser still assumed the body would be JSON and tried to parse it, and failed.

**As a work-around,** we could fix our unit tests to provide a Content-Type and request body -- even though these make no sense for a GET request:

```python
rv = client.get("/v1/users",
    headers={"Content-Type": "application/json"},
    data=json.dumps({}),
)
```

Exception traceback:

```
Traceback (most recent call last):
  File "/home/kirsle/.virtualenvs/within_auth34/lib/python3.4/site-packages/webargs/flaskparser.py", line 65, in parse_json
    self._cache["json"] = json_data = core.parse_json(data)
  File "/home/kirsle/.virtualenvs/within_auth34/lib/python3.4/site-packages/webargs/core.py", line 128, in parse_json
    return json.loads(s)
  File "/usr/lib64/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kirsle/.virtualenvs/within_auth34/lib/python3.4/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kirsle/.virtualenvs/within_auth34/lib/python3.4/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kirsle/work/within_auth/within_auth/controllers/api/decorators.py", line 79, in decorated_function
    return f(*args, **kwargs)
  File "/home/kirsle/.virtualenvs/within_auth34/lib/python3.4/site-packages/webargs/core.py", line 436, in wrapper
    error_headers=error_headers,
  File "/home/kirsle/.virtualenvs/within_auth34/lib/python3.4/site-packages/webargs/core.py", line 344, in parse
    parsed = self._parse_request(schema=schema, req=req, locations=locations)
  File "/home/kirsle/.virtualenvs/within_auth34/lib/python3.4/site-packages/webargs/core.py", line 259, in _parse_request
    parsed_value = self.parse_arg(argname, field_obj, req, locations)
  File "/home/kirsle/.virtualenvs/within_auth34/lib/python3.4/site-packages/webargs/core.py", line 231, in parse_arg
    value = self._get_value(name, field, req=req, location=location)
  File "/home/kirsle/.virtualenvs/within_auth34/lib/python3.4/site-packages/webargs/core.py", line 204, in _get_value
    value = function(req, name, argobj)
  File "/home/kirsle/.virtualenvs/within_auth34/lib/python3.4/site-packages/webargs/flaskparser.py", line 66, in parse_json
    except json.JSONDecodeError as e:
AttributeError: 'module' object has no attribute 'JSONDecodeError'
```

**Also note:** I could trigger this bug on Python 3.4.9 but it was not triggered on Python 3.6 or 3.7 strangely enough.

**Comment by sloria** [comment]
webargs does not officially support Python 3.4.

webargs 5.0 allows `JSONDecodeError` to be raised by `json.load` than handled in `handle_invalid_json_error`. `JSONDecodeError` does not exist in the `json` module in Python 3.4. You can work around this by installing `simplejson`, which webargs will use if it's installed.
