### ISSUE TITLE
required=True is not working with @post_load

### ISSUE THREAD

**Issue by AntonAleksandrov13** [marshmallow-code/webargs#619]
Hello, guys

I am not entirely sure if it's intended functionality, but I have encountered the following behaviour when using webargs with Flask application.

First example:
```
cronjob_args = {
    "job_name": fields.Str(required=True),
    "image": fields.Str(required=True),
    "source": fields.Str(required=True),
    "target": fields.Str(required=True),
    "schedule": fields.Str(required=True),
    "dry_run": fields.Str(required=True),
    "cross_account": fields.Str(required=True),
    "account": fields.Str(),
    "role": fields.Str()
}

@app.route("/api/task", methods=["POST"], strict_slashes=False)
@use_args(query_args, location="query")
@use_args(cronjob_args, location="json")
def create_task_controller(query_args, json_args):
 # receiving args from query and json locations
 # invoke corresponding service
 # or webargs throws 422 on missing param
```
In this scenario whenever one of the required params is not provided, the application would return 422 error. This is the expected behaviour since `required` flag is set to `True`.

Recently I have decided to combine my data model with arguments:
```
class CronJobSchema(Schema):
    job_name = fields.Str(required=True)
    image = fields.Str(required=True)
    source = fields.Str(required=True)
    target = fields.Str(required=True)
    schedule = fields.Str(required=True)
    dry_run = fields.Str(required=True)
    cross_account = fields.Str(required=True)
    account = fields.Str()
    role = fields.Str()

    @post_load
    def make_object(self, data, **kwargs):
        return CronJob(job_name=data['job_name'], source=data['source'], target=data['target'], image=data['image'],
                       schedule=data['schedule'],
                       dry_run=str_to_bool(data['dry_run']),
                       cross_account=str_to_bool(data['cross_account']),
                       account=None if not 'account' in data else data['account'],
                       role=None if not 'role' in data else data['role'])

```
As you can see in post_load function I am creating a Python object based on `CronJobSchema`. However, if I don't provide one of the arguments, the application will return 500 instead of expected 422 when its unable one of the params in `data` dictionary.

```
webargs==7.0.1
marshmallow==3.10.0
```

**Comment by lafrech** [comment]
Strange. Can you please share a traceback?

And perhaps try to load the data directly in the marshmallow schema (without Flask/webargs), to see what happens.

**Comment by AntonAleksandrov13** [comment]
Here's the traceback:
```
Traceback (most recent call last):
  File "/Users/aalek2/Projects/emea-platform-syncserver-v2/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/aalek2/Projects/emea-platform-syncserver-v2/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/aalek2/Projects/emea-platform-syncserver-v2/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/aalek2/Projects/emea-platform-syncserver-v2/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/aalek2/Projects/emea-platform-syncserver-v2/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/aalek2/Projects/emea-platform-syncserver-v2/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/aalek2/Projects/emea-platform-syncserver-v2/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/aalek2/Projects/emea-platform-syncserver-v2/venv/lib/python3.8/site-packages/webargs/core.py", line 445, in wrapper
    return func(*args, **kwargs)
  File "/Users/aalek2/Projects/emea-platform-syncserver-v2/venv/lib/python3.8/site-packages/webargs/core.py", line 433, in wrapper
    parsed_args = self.parse(
  File "/Users/aalek2/Projects/emea-platform-syncserver-v2/venv/lib/python3.8/site-packages/webargs/core.py", line 323, in parse
    data = schema.load(location_data, **load_kwargs)
  File "/Users/aalek2/Projects/emea-platform-syncserver-v2/venv/lib/python3.8/site-packages/marshmallow/schema.py", line 727, in load
    return self._do_load(
  File "/Users/aalek2/Projects/emea-platform-syncserver-v2/venv/lib/python3.8/site-packages/marshmallow/schema.py", line 897, in _do_load
    result = self._invoke_load_processors(
  File "/Users/aalek2/Projects/emea-platform-syncserver-v2/venv/lib/python3.8/site-packages/marshmallow/schema.py", line 1095, in _invoke_load_processors
    data = self._invoke_processors(
  File "/Users/aalek2/Projects/emea-platform-syncserver-v2/venv/lib/python3.8/site-packages/marshmallow/schema.py", line 1227, in _invoke_processors
    data = processor(data, many=many, **kwargs)
  File "/Users/aalek2/Projects/emea-platform-syncserver-v2/app/model/cronjob.py", line 80, in make_object
    cross_account=str_to_bool(data['cross_account']),
  File "/Users/aalek2/Projects/emea-platform-syncserver-v2/app/util/util.py", line 28, in str_to_bool
    raise ValueError
ValueError

```
It fails in my method called `str_to_bool`. Here's it's code:

```
def str_to_bool(s):
    if s == 'True' or s == 'true':
        return True
    elif s == 'False' or s == 'false':
        return False
    else:
        raise ValueError
```

**My assumption would that if a property is missing, I would get 422 before `@post_load` call. 
In reality it seems that a missing property is set to an empty string. As `str_to_bool` receives an empty string it throws an exception.**


I will try experimenting with loading the data directly in the marshmallow schema later. I will let you know

**Comment by lafrech** [comment]
Could it be the frontend sending empty strings when inputs are empty?

Either the frontend should send no value, either a pre-load of some kind should remove empty strings.

**Comment by AntonAleksandrov13** [comment]
oh, you are right. I thought it's been handled on the client-side as well
Sorry for raising a fuss
